# Generated by Django 4.1.7 on 2023-03-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='gpt-3.5-turbo-0301', max_length=180)),
                ('prompt', models.TextField(default='Respondeme cualquier cosa en frances')),
                ('temperature', models.FloatField(default=1)),
                ('max_tokens', models.IntegerField(default=1000)),
                ('top_p', models.FloatField(default=1)),
                ('n', models.IntegerField(default=1)),
                ('stream', models.BooleanField(default=False)),
                ('presence_penalty', models.FloatField(default=0)),
                ('frequency_penalty', models.FloatField(default=0)),
            ],
        ),
    ]
